// Copyright Dan Price 2026.

//////////////////////////////////
////  GENERATED BY bessel.py  ////
////  DO NOT EDIT MANUALLY!!  ////
//////////////////////////////////

#pragma once

#include <cstddef>

namespace json2wav
{
	constexpr const size_t NUM_BESSEL_ORDERS = 4;
	constexpr const size_t NUM_POSITIVE_BESSEL_ZEROS_PER_ORDER = 128;
	extern const float bessel_harmonics_by_order[NUM_BESSEL_ORDERS][NUM_POSITIVE_BESSEL_ZEROS_PER_ORDER];
	extern const float bessel_harmonics[];
	extern const size_t NUM_BESSEL_HARMONICS;
	// Fast approximation of Bessel functions of the first kind,
	// with first positive zero normalized to 1
	float fast_jn_norm(const size_t n, const float x);
}

