// Copyright Dan Price 2026.

////////////////////////////////////
////////////////////////////////////
////    GENERATED BY drum.py    ////
////    DO NOT EDIT MANUALLY!   ////
////////////////////////////////////
////////////////////////////////////

// Generated using the following parameters:
// max_deviation = 0.2
// num_orders = 4
// num_zeros = 128
// num_tips = 21
// exp_base = 1.0
// d = 0.0005

#pragma once

#include "DrumHitTypes.h"
#include <cstddef>

namespace DrumHit
{
	extern const Array<const Array<const Array<const PolyType, 20>, 128>, 4> splines;
	FloatType ModeAmp(const size_t order, const size_t zero, const FloatType hit_pos);
	constexpr const FloatType maxDeviation = 0.2;
}

