// Copyright Dan Price. All rights reserved.

/////////////////////////////////////
////  Generated by transient.py  ////
////  !!DO NOT EDIT MANUALLY!!!  ////
/////////////////////////////////////

#pragma once

#include "FastSin.h"

namespace json2wav::RampDetail
{
	template<typename FloatType>
	inline FloatType HitPoly262(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (1/3, 2):     f(1/3) = 2
		 * 4) 1st derivative 0 at start: f'(0) = 0
		 * 5) 2nd derivative 0 at start: f''(0) = 0
		 * 6) 1st derivative 0 at end:   f'(1) = 0
		 * 7) 2nd derivative 0 at end:   f''(1) = 0
		 * 8) 3rd derivative 0 at end:   f'''(1) = 0
		 * 9) 4th derivative 0 at end:   f''''(1) = 0
		 * 10) 5th derivative 0 at end:  f'''''(1) = 0
		 * 11) 6th derivative 0 at end:  f''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(-635.3203125450121);
		static const FloatType b = static_cast<FloatType>(4475.242187813097);
		static const FloatType c = static_cast<FloatType>(-13530.726563431885);
		static const FloatType d = static_cast<FloatType>(22776.210939037348);
		static const FloatType e = static_cast<FloatType>(-23076.210939016255);
		static const FloatType f = static_cast<FloatType>(14097.726563391587);
		static const FloatType g = static_cast<FloatType>(-4825.2421877871575);
		static const FloatType h = static_cast<FloatType>(719.3203125377962);

		return (((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x*x*x;
	}

	template<typename FloatType>
	inline FloatType HitPoly272(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (13/42, 2):   f(13/42) = 2
		 * 4) 1st derivative 0 at start: f'(0) = 0
		 * 5) 2nd derivative 0 at start: f''(0) = 0
		 * 6) 1st derivative 0 at end:   f'(1) = 0
		 * 7) 2nd derivative 0 at end:   f''(1) = 0
		 * 8) 3rd derivative 0 at end:   f'''(1) = 0
		 * 9) 4th derivative 0 at end:   f''''(1) = 0
		 * 10) 5th derivative 0 at end:  f'''''(1) = 0
		 * 11) 6th derivative 0 at end:  f''''''(1) = 0
		 * 12) 7th derivative 0 at end:  f'''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(886.2548551422004);
		static const FloatType b = static_cast<FloatType>(-7126.038841056202);
		static const FloatType c = static_cast<FloatType>(25095.135943351983);
		static const FloatType d = static_cast<FloatType>(-50575.27188585318);
		static const FloatType e = static_cast<FloatType>(63837.83985597217);
		static const FloatType f = static_cast<FloatType>(-51730.27188337677);
		static const FloatType g = static_cast<FloatType>(26327.13594073976);
		static const FloatType h = static_cast<FloatType>(-7720.038839824188);
		static const FloatType i = static_cast<FloatType>(1006.2548549030713);

		return ((((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x + i)*x*x*x;
	}

	template<typename FloatType>
	inline FloatType HitPoly282(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (2/7, 2):     f(2/7) = 2
		 * 4) 1st derivative 0 at start: f'(0) = 0
		 * 5) 2nd derivative 0 at start: f''(0) = 0
		 * 6) 1st derivative 0 at end:   f'(1) = 0
		 * 7) 2nd derivative 0 at end:   f''(1) = 0
		 * 8) 3rd derivative 0 at end:   f'''(1) = 0
		 * 9) 4th derivative 0 at end:   f''''(1) = 0
		 * 10) 5th derivative 0 at end:  f'''''(1) = 0
		 * 11) 6th derivative 0 at end:  f''''''(1) = 0
		 * 12) 7th derivative 0 at end:  f'''''''(1) = 0
		 * 13) 8th derivative 0 at end:  f''''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(-1196.4673813207878);
		static const FloatType b = static_cast<FloatType>(10813.206431753355);
		static const FloatType c = static_cast<FloatType>(-43468.82572638531);
		static const FloatType d = static_cast<FloatType>(102043.26002648968);
		static const FloatType e = static_cast<FloatType>(-154219.8900365816);
		static const FloatType f = static_cast<FloatType>(155704.8900327181);
		static const FloatType g = static_cast<FloatType>(-105123.260018603);
		static const FloatType h = static_cast<FloatType>(45844.82572052181);
		static const FloatType i = static_cast<FloatType>(-11758.206429586435);
		static const FloatType j = static_cast<FloatType>(1361.4673809995875);

		return (((((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x + i)*x + j)*x*x*x;
	}

	template<typename FloatType>
	inline FloatType HitPoly292(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (5/19, 2):    f(5/19) = 2
		 * 4) 1st derivative 0 at start: f'(0) = 0
		 * 5) 2nd derivative 0 at start: f''(0) = 0
		 * 6) 1st derivative 0 at end:   f'(1) = 0
		 * 7) 2nd derivative 0 at end:   f''(1) = 0
		 * 8) 3rd derivative 0 at end:   f'''(1) = 0
		 * 9) 4th derivative 0 at end:   f''''(1) = 0
		 * 10) 5th derivative 0 at end:  f'''''(1) = 0
		 * 11) 6th derivative 0 at end:  f''''''(1) = 0
		 * 12) 7th derivative 0 at end:  f'''''''(1) = 0
		 * 13) 8th derivative 0 at end:  f''''''''(1) = 0
		 * 14) 9th derivative 0 at end:  f'''''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(1571.3435757814882);
		static const FloatType b = static_cast<FloatType>(-15768.435757613095);
		static const FloatType c = static_cast<FloatType>(71250.4609082324);
		static const FloatType d = static_cast<FloatType>(-190937.22908551508);
		static const FloatType e = static_cast<FloatType>(336142.1508934855);
		static const FloatType f = static_cast<FloatType>(-406373.5810638314);
		static const FloatType g = static_cast<FloatType>(341862.15087882755);
		static const FloatType h = static_cast<FloatType>(-197801.22906903425);
		static const FloatType i = static_cast<FloatType>(75462.4608994325);
		static const FloatType j = static_cast<FloatType>(-17198.435755399365);
		static const FloatType k = static_cast<FloatType>(1791.3435756367787);

		return ((((((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x + i)*x + j)*x + k)*x*x*x;
	}

	template<typename FloatType>
	inline FloatType HitPoly2A2(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (12/49, 2):   f(12/49) = 2
		 * 4) 1st derivative 0 at start: f'(0) = 0
		 * 5) 2nd derivative 0 at start: f''(0) = 0
		 * 6) 1st derivative 0 at end:   f'(1) = 0
		 * 7) 2nd derivative 0 at end:   f''(1) = 0
		 * 8) 3rd derivative 0 at end:   f'''(1) = 0
		 * 9) 4th derivative 0 at end:   f''''(1) = 0
		 * 10) 5th derivative 0 at end:  f'''''(1) = 0
		 * 11) 6th derivative 0 at end:  f''''''(1) = 0
		 * 12) 7th derivative 0 at end:  f'''''''(1) = 0
		 * 13) 8th derivative 0 at end:  f''''''''(1) = 0
		 * 14) 9th derivative 0 at end:  f'''''''''(1) = 0
		 * 15) 10th derivative 0 at end: f''''''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(-2017.168616967889);
		static const FloatType b = static_cast<FloatType>(22254.85479167781);
		static const FloatType c = static_cast<FloatType>(-111659.27398803252);
		static const FloatType d = static_cast<FloatType>(336342.8220704468);
		static const FloatType e = static_cast<FloatType>(-675961.6443997655);
		static const FloatType f = static_cast<FloatType>(951951.9026103159);
		static const FloatType g = static_cast<FloatType>(-958958.9031857869);
		static const FloatType h = static_cast<FloatType>(691405.6456757681);
		static const FloatType i = static_cast<FloatType>(-349992.82321305806);
		static const FloatType j = static_cast<FloatType>(118666.27458810012);
		static const FloatType k = static_cast<FloatType>(-24333.854976604383);
		static const FloatType l = static_cast<FloatType>(2303.1686440840517);

		return (((((((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x + i)*x + j)*x + k)*x + l)*x*x*x;
	}

	template<typename FloatType>
	inline FloatType HitPoly2624(const FloatType x) noexcept
	{
		static_assert(IsFloatType<FloatType>::value, "json2wav::RampDetail::HitPoly() only operates on float types");

		/** Polynomial on [0, 1] with the following constraints:
		 * 1) Start at 0:                f(0) = 0
		 * 2) End at 1:                  f(1) = 1
		 * 3) Pass through (0.085, 0.5): f(0.085) = 0.5
		 * 4) Pass through (0.17, 1.5):  f(0.17) = 1.5
		 * 5) Pass through (0.29, 2):    f(0.29) = 2
		 * 6) Pass through (0.43, 1.7):  f(0.43) = 1.7
		 * 7) 1st derivative 0 at start: f'(0) = 0
		 * 8) 2nd derivative 0 at start: f''(0) = 0
		 * 9) 1st derivative 0 at end:   f'(1) = 0
		 * 10) 2nd derivative 0 at end:  f''(1) = 0
		 * 11) 3rd derivative 0 at end:  f'''(1) = 0
		 * 12) 4th derivative 0 at end:  f''''(1) = 0
		 * 13) 5th derivative 0 at end:  f'''''(1) = 0
		 * 14) 6th derivative 0 at end:  f''''''(1) = 0
		 */

		static const FloatType a = static_cast<FloatType>(12942.388959867767);
		static const FloatType b = static_cast<FloatType>(-109272.9898047578);
		static const FloatType c = static_cast<FloatType>(411630.39540307946);
		static const FloatType d = static_cast<FloatType>(-910987.149735213);
		static const FloatType e = static_cast<FloatType>(1312316.4388875705);
		static const FloatType f = static_cast<FloatType>(-1287576.93394551);
		static const FloatType g = static_cast<FloatType>(874070.68275806);
		static const FloatType h = static_cast<FloatType>(-407759.60275293584);
		static const FloatType i = static_cast<FloatType>(126382.67078238772);
		static const FloatType j = static_cast<FloatType>(-23886.324370024548);
		static const FloatType k = static_cast<FloatType>(2141.4238174567727);

		return ((((((((((a*x + b)*x + c)*x + d)*x + e)*x + f)*x + g)*x + h)*x + i)*x + j)*x + k)*x*x*x;
	}
}

